### ISSUE TITLE
Checklist!

### ISSUE THREAD

**Issue by devdrops** [php-do-jeito-certo/telegram-post-bot#1]
Passos importantes para finalização:

* [x] Integração com Twitter (https://dev.twitter.com/rest/public);
* [x] Deploy no Heroku de forma segura: sem chaves comitadas!
    * Se não rolar isso no Heroku, usar outra hospedagem. Checar https://devcenter.heroku.com/articles/config-vars para mais detalhes.
* [ ] Uso seguro: acesso restrito ao nosso querido bot para somente o nosso grupo :heart: (checar https://core.telegram.org/bots)
* [ ] Interpretar metadata do link no comando `/tweet` para formar o que vai ser tweetado (http://php.net/get_meta_tags);
* [ ] Detalhes finais do bot: imagem, descrição, etc.

Passos futuros:

* [ ] Integrar com Facebook (novo comando `/post`)

**Owners**: a casa é nossa.
